### ISSUE TITLE
This project is currently not under active development

### ISSUE THREAD

**Issue by bzvestey** [SAML-Toolkits/python3-saml#320]
Hello everyone, we here at OneLogin wanted to let you know that this project is currently not under active development. We apologize for recent silence and continued wait, but we intend to resume maintenance in the future.

Note that I am unable to make any more changes to this repository, and I don't have someone I can forward you to at this time.

**Comment by pitbulk** [comment]
@mbertrand I plan to keep support of python3-saml and the other SAML toolkits. I contacted OneIdentity/OneLogin in order to see how make it possible.

**Comment by bzvestey** [comment]
More conversation can be found on the java-saml project's issue here https://github.com/onelogin/java-saml/issues/388

**Comment by dolsysmith** [comment]
@pitbulk Are you still planning to support this going forward? Or are there any other updates from OneLogin that you can share?

**Comment by pitbulk** [comment]
Im still waiting

**Comment by valberg** [comment]
Could it be an idea to see if we could adopt python3-saml as a part of https://jazzband.co?

**Comment by mrmoss** [comment]
cc @eriktalvi

**Comment by stabacco** [comment]
Does anyone know any alternative packages, since this is unmantained?

**Comment by eriktalvi** [comment]
Development Update. OneLogin is releasing these projects to a new organization with @pitbulk. This migration is actively happening and the priority is to make the transition as seamless as possible for end users of these repo/packages.

We expect that there are several questions that you all have and we are working with @pitbulk to answer those in our next update. Below are some answers we have for you now.

What is being changed?
The repos/packages will no longer be officially supported and hosted by OneLogin. This means that they will not be in the OneLogin Github org but in a new org, SAML Tools. References to the repos being provided and supported by OneLogin Inc will be removed.

Which projects are being moved?
All SAML repos will be moved. This includes: java-saml, python3-saml, wordpress-saml, moodle-saml, joomla-saml, drupal-saml, and dotnet-saml

When will this transfer happen?
We expect this to be completed by the end of the year, Dec 31 2022.

Why is this transfer happening?
OneLogin is releasing control of these open source repos so that these repos can maintained by community instead.

When will the next update be?
To keep you all informed of status, we will give monthly updates of how the transfer is proceeding.

**Comment by nosnilmot** [comment]
> Development Update. OneLogin is releasing these projects to a new organization with @pitbulk. This migration is actively happening and the priority is to make the transition as seamless as possible for end users of these repo/packages.

Thanks for the update @eriktalvi

It's great to see that progress is being made, but is there a possibility of merging PR #323 and cutting a new release of `python3-saml` without having to wait for this transfer to complete? without it users are a) blocked from upgrading to python 3.11 (cf. #328) and b) forced to use old LXML with known security vulnerabilities (#319)

**Comment by macwilk** [comment]
Awesome to see! 

We use this library at [Alloy](https://www.alloy.com/) and ended up finding a way to address the lxml bug in a fork that we're using [here](https://github.com/UseAlloy/python3-saml/blob/master/requirements.txt#L1) for anyone curious.

Excited to see what the future of this lib entails and the possibility of contributing some of our changes downstream!

**Comment by ThiefMaster** [comment]
@eriktalvi and/or @pitbulk a timely release containing #323 would indeed be greatly appreciated - if that could be done before finalizing all the stuff  regarding the move, I think everyone using your library would appreciate it!

**Comment by eriktalvi** [comment]
Development Update. Although it may not seem like it, the last month had a lot of progress and the primary SAML Toolkit repos and packages have been transferred from OneLogin to this new SAML Toolkit Org.

@pitbulk now has all the access needed to maintain these toolkits and will be providing his own update.

There has been a lot of pent up demand for support on these repos (especially this one) and now that this transfer is finished you should expect to see a lot more progress on that!

There are still four repos (wordpress-saml, moodle-saml, joomla-saml, drupal-saml) left to transfer and these will be finished in the upcoming weeks.

Cheers!

**Comment by pitbulk** [comment]
Closing this, as I gonna maintain this repo.
